name: Deploy to sample-pro-395702 Cloud Run

on:
  push:
    branches:
      - go-gcp-tf-github_actions

env:
  GCP_PROJECT_ID: "sample-pro-395702"
  GCP_REGION: "asia-northeast1"
  IMAGE_NAME: asia-northeast1-docker.pkg.dev/sample-pro-395702/artifacts/sample-app-001-server
  SERVICE_NAME: sample-app-001

jobs:
  deploy-to-sample-pro-395702-cloud-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        run: |
          TAG=$(echo $GITHUB_SHA | head -c7)
          gcloud auth configure-docker asia-northeast1-docker.pkg.dev
          docker build -t ${IMAGE_NAME}:${TAG} -f services/app-001/backend/app.Dockerfile services/app-001/backend/
          docker push ${IMAGE_NAME}:${TAG}

      - name: Deploy to Cloud Run
        run: |
          TAG=$(echo $GITHUB_SHA | head -c7)
          gcloud run deploy ${SERVICE_NAME} \
            --image ${IMAGE_NAME}:${TAG} \
            --platform managed \
            --region ${GCP_REGION} \
            --allow-unauthenticated
